/**
 * PolyFit Master Constants & Configuration
 * East Africa / Rwanda Corporate Wellness Network
 */

export interface RwandanBank {
  name: string;
  swift: string;
}

export const RWANDAN_BANKS: RwandanBank[] = [
  { name: 'Bank of Kigali (BK)', swift: 'BKIGRWRW' },
  { name: 'I&M Bank Rwanda', swift: 'BCRWRWRW' },
  { name: 'Equity Bank Rwanda', swift: 'EQBLRWRW' },
  { name: 'BPR Bank Rwanda (Atlas Mara)', swift: 'BPRWRWRW' },
  { name: 'Ecobank Rwanda', swift: 'ECOCRWRW' },
  { name: 'Cogebanque (Equity)', swift: 'COGBRWRW' },
  { name: 'NCBA Bank Rwanda', swift: 'NCBARWRW' },
  { name: 'Access Bank Rwanda', swift: 'ACCERWRW' }
];

export const RWANDA_TAX_RATES = {
  WITHHOLDING_TAX_WITH_TIN: 0.15,    // 15% standard withholding tax with valid RRA TIN
  WITHHOLDING_TAX_NO_TIN: 0.30       // 30% punitive withholding without registered TIN
} as const;

export const POLYFIT_SETTLEMENT_RULES = {
  PAYOUT_DAY_OF_MONTH: 15,          // 15th of the month
  CLAIMS_CUTOFF_DAY_OF_MONTH: 2,    // 2nd day of the month
  DEFAULT_GATE_RELAY_MS: 3000,      // 3-second NC/NO relay trigger
  CHECKIN_EXPIRATION_MINUTES: 20    // 20-minute validation SLA
} as const;

/**
 * Canonical Synchronized Enterprise Dataset (TechCorp Rwanda)
 * Shared single source of truth across Dashboard (PF-89), Roster (PF-90), Plans (PF-91), and Billing (PF-92)
 */
export const TECHCORP_CANONICAL_DATA = {
  organization: {
    id: "c79a9982-4477-4336-a24b-561419f6c43b",
    name: "TechCorp Rwanda",
    slug: "techcorp-rwanda",
    domain: "techcorp.rw",
    allowed_domains: ["techcorp.rw"],
    tax_id: "108392019",
    contact_email: "hr@techcorp.rw",
    billing_email: "finance@techcorp.rw",
    industry: "Technology",
  },
  plans: [
    {
      id: "7fbc45e1-318e-404a-90c4-f8b13cede34a",
      name: "TechCorp Executive Wellness Tier",
      tier: "executive",
      status: "active",
      max_monthly_visits: 16,
      co_pay_percentage: 0,
      allowed_provider_categories: ["gym", "pool", "studio", "clinic", "wellness_center"],
      budget_cap_per_employee: 120000,
      is_family_eligible: true,
      description: "Unrestricted access across all network venues including boutique studios and physio clinics. 100% employer subsidized.",
      enrolled_count: 12,
      departments: ["Executive", "Finance"],
      department_counts: { Executive: 4, Finance: 8 },
      estimated_monthly_liability: 960000,
    },
    {
      id: "2cc47686-dc6a-492b-bb88-832716809ac8",
      name: "TechCorp Premium Wellness Plan",
      tier: "premium",
      status: "active",
      max_monthly_visits: 20,
      co_pay_percentage: 0,
      allowed_provider_categories: ["gym", "pool", "studio", "clinic", "wellness_center"],
      budget_cap_per_employee: 80000,
      is_family_eligible: true,
      description: "Full network tier covering fitness clubs, Olympic lap pools, and recovery sessions. 100% covered.",
      enrolled_count: 38,
      departments: ["Engineering", "Finance"],
      department_counts: { Engineering: 26, Finance: 12 },
      estimated_monthly_liability: 1900000,
    },
    {
      id: "5894f62b-01f2-485e-8083-45565786c5d7",
      name: "TechCorp Standard Wellness Plan",
      tier: "standard",
      status: "active",
      max_monthly_visits: 8,
      co_pay_percentage: 15,
      allowed_provider_categories: ["gym", "pool", "studio"],
      budget_cap_per_employee: 60000,
      is_family_eligible: false,
      description: "Core corporate wellness benefit covering premium gyms, lap pools, and yoga studios with 15% co-pay.",
      enrolled_count: 85,
      departments: ["Engineering", "Marketing", "HR", "Sales"],
      department_counts: { Engineering: 42, Marketing: 22, HR: 9, Sales: 12 },
      estimated_monthly_liability: 2422500,
    },
    {
      id: "232512d0-0cc1-47fa-ad8b-e017bd598b6f",
      name: "TechCorp Basic Wellness Plan",
      tier: "basic",
      status: "active",
      max_monthly_visits: 4,
      co_pay_percentage: 20,
      allowed_provider_categories: ["gym", "pool"],
      budget_cap_per_employee: 30000,
      is_family_eligible: false,
      description: "Essential fitness benefit for shift and operations teams. Covers network gyms and public lap pools.",
      enrolled_count: 15,
      departments: ["Operations"],
      department_counts: { Operations: 15 },
      estimated_monthly_liability: 180000,
    },
  ],
  economics: {
    currentBalance: 3127000,
    currentInvoiceRwf: 2271500,
    invoiceStatus: "overdue" as const,
    invoiceNumber: "PF-INV-2026-09-0045",
    overdueAmount: 2271500,
    overdueInvoiceNumber: "PF-INV-2026-09-0045",
    hasOverdue: true,
    overdueDays: 5,
    dueDateStr: "Sep 30, 2026",
    ytdTotalSpent: 6785000,
    ytdTotalVisits: 1150,
    pmpmSpendRwf: 15143,
    avgCostPerVisit: 5900,
    citTaxShieldRwf: 2035500,
  },
  wellness: {
    wellnessHour: "17:00 - 18:00",
    peakDay: "Wednesday",
    categories: {
      gym: 195,
      pool: 95,
      studio: 55,
      clinic: 40,
    },
  },
  funnel: {
    totalEligible: 150,
    registeredEmployees: 118,
    activeBeneficiaries: 85,
    totalVisits: 385,
    newEmployees30d: 14,
    newBeneficiaries30d: 8,
    avgVisitsPerActive: 4.5,
  },
  invoices: [
    {
      id: "d1808cf2-9374-4824-ab4a-425b7eb4df14",
      invoice_number: "PF-INV-2026-10-0082",
      billing_period_start: "2026-10-01",
      billing_period_end: "2026-10-31",
      total_visits: 145,
      total_amount: 855500,
      tax_amount: 130500,
      status: "sent",
      due_date: "2026-11-15",
      created_at: "2026-09-28T09:00:00Z",
      organizations: {
        name: "TechCorp Rwanda",
        tax_id: "108392019",
        billing_email: "finance@techcorp.rw",
      },
    },
    {
      id: "dbfdf617-718a-4261-99a0-e325066359b8",
      invoice_number: "PF-INV-2026-09-0045",
      billing_period_start: "2026-09-01",
      billing_period_end: "2026-09-30",
      total_visits: 385,
      total_amount: 2271500,
      tax_amount: 346500,
      status: "overdue",
      due_date: "2026-09-25",
      created_at: "2026-09-20T08:00:00Z",
      organizations: {
        name: "TechCorp Rwanda",
        tax_id: "108392019",
        billing_email: "finance@techcorp.rw",
      },
    },
    {
      id: "56275ee0-907e-4d63-af95-b2dbaa7587c5",
      invoice_number: "PF-INV-2026-08-0027",
      billing_period_start: "2026-08-01",
      billing_period_end: "2026-08-31",
      total_visits: 340,
      total_amount: 2006000,
      tax_amount: 306000,
      status: "paid",
      due_date: "2026-09-30",
      paid_at: "2026-09-12T10:15:00Z",
      created_at: "2026-08-31T23:59:00Z",
      organizations: {
        name: "TechCorp Rwanda",
        tax_id: "108392019",
        billing_email: "finance@techcorp.rw",
      },
    },
    {
      id: "ae13f670-5016-4ad3-ba31-49417a4c4b2c",
      invoice_number: "PF-INV-2026-07-0014",
      billing_period_start: "2026-07-01",
      billing_period_end: "2026-07-31",
      total_visits: 280,
      total_amount: 1652000,
      tax_amount: 252000,
      status: "paid",
      due_date: "2026-08-30",
      paid_at: "2026-08-18T14:32:00Z",
      created_at: "2026-07-31T23:59:00Z",
      organizations: {
        name: "TechCorp Rwanda",
        tax_id: "108392019",
        billing_email: "finance@techcorp.rw",
      },
    },
  ],
  employees: [
    {
      id: "00fbe4e1-86aa-44bc-ad89-fcce6fb75687",
      full_name: "Jean Mugabo",
      email: "jean.mugabo@techcorp.rw",
      employee_id_external: "EMP001",
      department: "Engineering",
      tier: "standard",
      status: "active",
      created_at: "2026-01-15T08:30:00Z",
      visits_this_month: 8,
      eligibility: {
        id: "elig-1",
        status: "active",
        benefits: {
          id: "5894f62b-01f2-485e-8083-45565786c5d7",
          name: "TechCorp Standard Wellness Plan",
          tier: "standard",
          max_monthly_visits: 8,
          co_pay_percentage: 15,
        },
      },
      recent_visits: [
        {
          id: "v-1",
          check_in_at: "2026-09-28T17:15:00Z",
          verification_method: "totp_qr",
          status: "verified",
          provider_locations: {
            id: "loc-1",
            name: "Kigali Central Facility",
            city: "Kigali",
            providers: { id: "p-1", name: "Waka Fitness", category: "gym" },
          },
        },
        {
          id: "v-2",
          check_in_at: "2026-09-25T18:00:00Z",
          verification_method: "totp_qr",
          status: "verified",
          provider_locations: {
            id: "loc-2",
            name: "Cercle Sportif de Kigali",
            city: "Kigali",
            providers: { id: "p-2", name: "Cercle Sportif", category: "pool" },
          },
        },
      ],
    },
    {
      id: "3e501231-7097-4e78-9c0e-445bcbafd0e9",
      full_name: "Marie Uwimana",
      email: "marie.uwimana@techcorp.rw",
      employee_id_external: "EMP002",
      department: "Marketing",
      tier: "standard",
      status: "active",
      created_at: "2026-02-01T09:00:00Z",
      visits_this_month: 6,
      eligibility: {
        id: "elig-2",
        status: "active",
        benefits: {
          id: "5894f62b-01f2-485e-8083-45565786c5d7",
          name: "TechCorp Standard Wellness Plan",
          tier: "standard",
          max_monthly_visits: 8,
          co_pay_percentage: 15,
        },
      },
      recent_visits: [
        {
          id: "v-3",
          check_in_at: "2026-09-27T07:30:00Z",
          verification_method: "totp_qr",
          status: "verified",
          provider_locations: {
            id: "loc-1",
            name: "Kigali Central Facility",
            city: "Kigali",
            providers: { id: "p-1", name: "Waka Fitness", category: "gym" },
          },
        },
      ],
    },
    {
      id: "378d7933-329a-441a-acbe-21607e80191d",
      full_name: "Patrick Niyonzima",
      email: "patrick.niyonzima@techcorp.rw",
      employee_id_external: "EMP003",
      department: "Finance",
      tier: "premium",
      status: "active",
      created_at: "2026-02-15T10:15:00Z",
      visits_this_month: 16,
      eligibility: {
        id: "elig-3",
        status: "active",
        benefits: {
          id: "2cc47686-dc6a-492b-bb88-832716809ac8",
          name: "TechCorp Premium Wellness Plan",
          tier: "premium",
          max_monthly_visits: 20,
          co_pay_percentage: 0,
        },
      },
      recent_visits: [
        {
          id: "v-4",
          check_in_at: "2026-09-28T06:45:00Z",
          verification_method: "totp_qr",
          status: "verified",
          provider_locations: {
            id: "loc-3",
            name: "Nyashad Pilates & Wellness",
            city: "Kigali",
            providers: { id: "p-3", name: "Nyashad Studios", category: "studio" },
          },
        },
      ],
    },
    {
      id: "489bd7e2-393c-4b40-ade5-3832829053a6",
      full_name: "Claudine Mukandekeza",
      email: "claudine.mukandekeza@techcorp.rw",
      employee_id_external: "EMP004",
      department: "HR",
      tier: "standard",
      status: "frozen",
      created_at: "2026-03-01T11:00:00Z",
      visits_this_month: 2,
      eligibility: {
        id: "elig-4",
        status: "suspended",
        benefits: {
          id: "5894f62b-01f2-485e-8083-45565786c5d7",
          name: "TechCorp Standard Wellness Plan",
          tier: "standard",
          max_monthly_visits: 8,
          co_pay_percentage: 15,
        },
      },
    },
    {
      id: "a2e591aa-73e9-4dd4-a141-508551372ec0",
      full_name: "Eric Habimana",
      email: "eric.habimana@techcorp.rw",
      employee_id_external: "EMP005",
      department: "Operations",
      tier: "basic",
      status: "active",
      created_at: "2026-03-10T14:20:00Z",
      visits_this_month: 3,
      eligibility: {
        id: "elig-5",
        status: "active",
        benefits: {
          id: "232512d0-0cc1-47fa-ad8b-e017bd598b6f",
          name: "TechCorp Basic Wellness Plan",
          tier: "basic",
          max_monthly_visits: 4,
          co_pay_percentage: 20,
        },
      },
    },
    {
      id: "9912aa44-8833-4df1-8844-332211aabbcc",
      full_name: "Alice Gasana",
      email: "alice.gasana@techcorp.rw",
      employee_id_external: "EMP006",
      department: "Engineering",
      tier: "premium",
      status: "active",
      created_at: "2026-04-05T09:30:00Z",
      visits_this_month: 12,
      eligibility: {
        id: "elig-6",
        status: "active",
        benefits: {
          id: "2cc47686-dc6a-492b-bb88-832716809ac8",
          name: "TechCorp Premium Wellness Plan",
          tier: "premium",
          max_monthly_visits: 20,
          co_pay_percentage: 0,
        },
      },
    },
    {
      id: "aa88bb77-1122-4455-8899-ccddeeff0011",
      full_name: "David Karekezi",
      email: "david.karekezi@techcorp.rw",
      employee_id_external: "EMP007",
      department: "Sales",
      tier: "standard",
      status: "active",
      created_at: "2026-05-12T13:45:00Z",
      visits_this_month: 7,
      eligibility: {
        id: "elig-7",
        status: "active",
        benefits: {
          id: "5894f62b-01f2-485e-8083-45565786c5d7",
          name: "TechCorp Standard Wellness Plan",
          tier: "standard",
          max_monthly_visits: 8,
          co_pay_percentage: 15,
        },
      },
    },
    {
      id: "cc33dd44-5566-7788-9900-112233445566",
      full_name: "Grace Umutoni",
      email: "grace.umutoni@techcorp.rw",
      employee_id_external: "EMP008",
      department: "Engineering",
      tier: "executive",
      status: "active",
      created_at: "2026-06-20T10:00:00Z",
      visits_this_month: 14,
      eligibility: {
        id: "elig-8",
        status: "active",
        benefits: {
          id: "7fbc45e1-318e-404a-90c4-f8b13cede34a",
          name: "TechCorp Executive Wellness Tier",
          tier: "executive",
          max_monthly_visits: 16,
          co_pay_percentage: 0,
        },
      },
    },
  ],
};
